### ISSUE TITLE
Missing Ui Elements

### ISSUE THREAD

**Issue by peter-gerhard** [sphereio/sphere-sunrise#109]
On implemented pdp (branch pdp) the elements for priceOld and the label for the color chooser are missing.
They are not empty, but are also missing if given a hardcoded String.

![screen shot 2015-07-20 at 14 14 00](https://cloud.githubusercontent.com/assets/4236201/8775593/033fc048-2eea-11e5-8c49-9d2508ee4999.png)

**Comment by trangng** [comment]
@JulianSamarjiev can you have a look please?

**Comment by schleichardt** [comment]
@peter-gerhard Is this still the case after the design update?

**Comment by peter-gerhard** [comment]
@schleichardt I fixed the color label, the element for priceOld is still missing

**Comment by trangng** [comment]
@JulianSamarjiev can you please check if the priceOld is still missing? thank you
