### ISSUE TITLE
Delivery and Returns

### ISSUE THREAD

**Issue by peter-gerhard** [sphereio/sphere-sunrise#110]
What do we want to show under "Delivery and Return" currently the json defines only a String.
There might be multiple ShippingMethods wich have multiple ShippingRates depending on the current Cart.

**Comment by trangng** [comment]
@peter-gerhard it would be great if this area would be editable. If customer have any delivery method or return policies. e.g.:
shipping costs
- Italy	9 EUR for orders less than 50 EUR, FREE for orders above 50 EUR
- European Union	12,90 EUR for orders less than 150 EUR	FREE for orders above 150 EUR
- All other countries	29 EUR	

return costs
- Italy	9 EUR	
- European Union	12,90 EUR	
- All other countries	29 EUR*	*+import fees
