### ISSUE TITLE
Product suggestions in PDP 

### ISSUE THREAD

**Issue by schleichardt** [sphereio/sphere-sunrise#117]
* (YOU MAY ALSO LIKE)

* [ ] show random products from the same gender and different category
* [ ] handle the exceptionally case that not enough products present

**Comment by peter-gerhard** [comment]
> 4 productIDs will be randomly shown from the same category or you can define a field for the 4 productIDs on the product which will be shown. tbd.

**Comment by peter-gerhard** [comment]
> algorithm for the "You may also like" section?:
4 products should be shown from

same gender
different categories

**Comment by trangng** [comment]
@peter-gerhard randomly

**Comment by peter-gerhard** [comment]
@trangng so show random products?

**Comment by trangng** [comment]
@peter-gerhard yes. show random products from the same gender and different category

**Comment by peter-gerhard** [comment]
@trangng does it really need to have a random factor? or do we just not further specify?
so if you go twice on the pdp for the same product, would you expect that:
a) the same suggestions are shown both time
b) different suggestions are shown
