### ISSUE TITLE
Breadcrumb PDP

### ISSUE THREAD

**Issue by elisabethschneider** [sphereio/sphere-sunrise#119]
follow the main category path - no link for the last category

Use a MASTER breadcrumb, that means build location-based breadcrumbs: show the user where the current page is located relevant to the whole structure of the site. Always use the same path whether the customer came from a category or via a brand page. Show the path from the main categories Women/Men/Accessories 

#### Example for PDP:
  1. Customer clicks on product in category shoes, then this is how the breadcrumb should look like:
Homepage> Women> Shoes> Sneaker> CHUCK TAYLOR ALL STAR OX CORE CANVAS - Sneaker - white Canvas
  2. Customer clicks on product in brand category/page Converse, then the breadcrumb should just look like the one above:
Homepage> Women> Shoes> Sneaker> CHUCK TAYLOR ALL STAR OX CORE CANVAS - Sneaker - white Canvas

(Example for POP:
Customer clicks from the navigation on category sneaker, then this is how the breadcrumb should look like: Homepage> Women> Shoes> Sneaker)

On PDP only use the product title, no brand otherwise is the breadcrumb too long

- On PDP only use the product title, no brand otherwise is the breadcrumb too long
- Only use for categories from 2. level and product detail page 
- Do not link the current page to itself (the last step in the breadcrumbs should be un-linked)
- Show hierarchy and not history. To go back, users use the browser’s back button. Replicating this facility defies the purpose of having breadcrumbs
- Not be too large. The breadcrumb trail is a secondary navigation aid and hence its size and prominence should be less than that of the primary navigation
- Progress from the highest level to the lowest, one step at a time
- Start with the homepage and end with the current page
- Have a simple link for each level (except for the current page). If the trail includes non clickable elements such as page titles then include them but clearly differentiate which parts are clickable
- Have a simple, one-character separator between each level (usually “>”)
- Not be cluttered with unnecessary text such as “You are here” or “Navigation”
- Add a title attribute as <a href="" title="Coat"/>

**Comment by butenkor** [comment]
@elisabethschneider How does breadcrumb look like if I navigate through brands or use search and selected product is assigned to following both categories? 

```Homepage> Women> Shoes> Sneaker``` 
```Homepage> Men> Shoes> Sneaker```

**Comment by trangng** [comment]
@butenkor ideal is to always use the same breadcrumb path for one product otherwise you have a problem with duplicate content. 

@peter-gerhard is it possible to implement for sunrise?

**Comment by butenkor** [comment]
Do you need to index breadcrumb for search engines? If not we can use "noindex" => no duplicate content. I think breadcrumb should represent the path of how the user got to PDP so that the user can always navigate back over breadcrumb. If breadcrumb is always the same it may be good for SEO but not for the user.

Suggestion:

Navigate to product over category:
```Homepage> Women> Shoes> Sneaker> CHUCK TAYLOR ALL STAR OX CORE CANVAS - Sneaker - white Canvas```

Navigate over brand:
```Homepage> Brands> Adidas> CHUCK TAYLOR ALL STAR OX CORE CANVAS - Sneaker - white Canvas```

Navigate over search:
```Homepage> Search Results > CHUCK TAYLOR ALL STAR OX CORE CANVAS - Sneaker - white Canvas```

**Comment by trangng** [comment]
@PeterRoman could you please give feedback here. thank you

**Comment by peter-gerhard** [comment]
@trangng @butenkor 
> I think breadcrumb should represent the path of how the user got to PDP

I would disagree here, users won't use breadcrumbs to backtrace their browser history, thats browser functionality. We should rather give a hint for the structure of the products and help find logically connected products.

what we have to think about is what happens if a product is in multiple categories.
as we don't have a main category, we can either
- show all paths
- show one random path

i'll go with the second option for mvp

**Comment by PeterRoman** [comment]
I like the original requirements from Elisabeth with one master-breadcrumb path. Also disagree that breadcrumb needs to represent the exact path. 

We had this discussion with several projects, e.g with KOK, where we have the category parameter to render the exact breadcrumb for additional paths via Themen, Sale:
http://www.kokon.com/decke-mashallah-vintage21048451-1.html?c=wohnen-decken-und-plaids-tagesdecken 

My conclusion: 
- follow original specs determined by elisabeth
- breadcrumb meant to "show hierarchy and not history". For history the user can use the back-button.
Zalando also implements a back-button in the breadcrumb on pdp-level:
https://www.zalando.de/versace-sneaker-high-black-1ve12b007-q11.html

Exact path leads to more confusion than benefit for the user to my mind.

**Comment by mmoelli** [comment]
:+1: for the master path
