### ISSUE TITLE
Product presentation PDP

### ISSUE THREAD

**Issue by elisabethschneider** [sphereio/sphere-sunrise#121]
Product: as default the master variant will be shown
Images: as default you are able to see the master image, on the left you are able to see the thumbnails for the image variants
Product information: next to the product images - article number, description, detail informations
Price: dependent on the choosen product, the IP (country) and the usergroup the price with the appropriate currency will be shown
Colour and size selector: dependent on the choosen colour variant you can see the available sizes
Quantity: you can insert a quantity up to 100 pieces. If there is an insufficient stock, you will get an error message
Size guide: if you click on the sizeguide a overlay with the measurements will be shown
Details: more details to the product will be shown
Delivery information: you can see the delivery and return information

**Comment by butenkor** [comment]
> Product: as default the master variant will be shown

On POP will be colour selector. If i click there on colour which is not master then PDP should open selected variant from POP, right?

**Comment by trangng** [comment]
@butenkor yes

**Comment by peter-gerhard** [comment]
* [ ] Product: as default the master variant will be shown
* [ ] Images: as default you are able to see the master image, on the left you are able to see the thumbnails for the variants images
* [ ] Product information: next to the product images - article number, description, detail informations
* [ ] Price: dependent on the chosen product, the IP (country) and the usergroup the price with the appropriate currency will be shown
* [ ] Colour selector: user can see available colours
* [ ] Size selector: user can see available sizes
* [ ] Quantity: you can insert a quantity up to 100 pieces. If there is an insufficient stock, you will get an error message
* [ ] Size guide: if you click on the sizeguide a overlay with the measurements will be shown
* [ ] Product Details: more details to the product will be shown
* [ ] Delivery information: you can see the delivery and return information

**Comment by peter-gerhard** [comment]
@trangng
https://sphere.atlassian.net/wiki/pages/viewpage.action?pageId=21757982
the url structure in the link suggests that we have one link per product variant 

> as default the master variant will be shown
suggests that we have one url per product

is there a final decision on that?

**Comment by peter-gerhard** [comment]
>Quantity [...] If there is an insufficient stock, you will get an error message
will be done when stock logic is added

**Comment by peter-gerhard** [comment]
> Size guide: if you click on the sizeguide a overlay with the measurements will be shown

https://github.com/sphereio/sphere-sunrise-design/issues/48

**Comment by peter-gerhard** [comment]
> Delivery information: you can see the delivery and return information

https://github.com/sphereio/sphere-sunrise-design/issues/49
#110

**Comment by peter-gerhard** [comment]
@trangng  I talked with @PeterRoman: decision here is url per product variant if you don't have any objections
