### ISSUE TITLE
image zoom PDP

### ISSUE THREAD

**Issue by elisabethschneider** [sphereio/sphere-sunrise#122]
with this view the customer is able to see the product in detail

**Comment by peter-gerhard** [comment]
what exactly do you meant with zoom? is this already implemented?
https://sunrise-pdp-demo.herokuapp.com/pdp

**Comment by trangng** [comment]
@peter-gerhard the zoom is the mouse over closeup. It's already implemented as I saw, so we can close this issue. thank you
