### ISSUE TITLE
Product presentation POP

### ISSUE THREAD

**Issue by elisabethschneider** [sphereio/sphere-sunrise#128]
- as default there are always 12 products  to show, but customer can change that.
- one row for brand and product title, will be shown under the product picture. Format of product title is brand - product title, for example Nike - AIR MAX 1.0
- one row for prices, will be shown under the title
- one row for available sizes, will be shown under the price

**Comment by butenkor** [comment]
Why only 12 products by default? Who does it nowadays? I would at least double it.
Why do you want to show sizes and not colours on POP? Or there will be both?

**Comment by trangng** [comment]
@butenkor 
- 12 products were defined in the designs, it's not a must. customer should be able to select how many he/she wants to see 
-both will be shown

**Comment by butenkor** [comment]
We should use defaults which will satisfy most customers without being forced to change it every time. Compare this default value with other popular shops.

**Comment by trangng** [comment]
will be fixed by another issue in sunrise-design
