### ISSUE TITLE
Sorting POP

### ISSUE THREAD

**Issue by elisabethschneider** [sphereio/sphere-sunrise#131]
default sorting is "new" products. the customer has an option to sort by low, high price, new and popular by choosing one from the drop down.

**Comment by butenkor** [comment]
Please define "new" and "popular".

**Comment by trangng** [comment]
@butenkor 
- new could be defined by my creation date everything newer then 4 weeks is new or alternative would be an attribute. from the development site what would you suggest?

- popular is defined by amount of sold products

**Comment by butenkor** [comment]
If you do not import products for 4 weeks then you will have no new products at all. Do you want to mark those products as new or just sort by creation date? If you do not want to control creation date manually then you do not need an additional attribute.

I do not think we have required Infos to sort by popularity yet. The easiest way is to control it over custom attribute manually for now.

**Comment by trangng** [comment]
- then I would offer both for new, with the creation date products will have the flag new and if ecom manager wants to set the flag manually he can set it by attribute "new"

- I'm fine with it for now. But for popularity it would make sense to automatize it. So at the moment we don't have any chance to track the sold amount right?

**Comment by butenkor** [comment]
I do not think you can do both because you sort either by custom attribute or createdAt provided by database. You have to decide if you wamt to have control over it or not. If yes then custom attribute.

There are some possibilities like:

- cronjob which iterates over products on orders and increases its popularity custom attribute by one.

- or do above as part of checkout (after order creation)

**Comment by lauraluiz** [comment]
Currently we sort by createdAt desc, price asc and price desc. When two values are the same, then we have always the createdAt as 2nd option (multisorting).
