### ISSUE TITLE
Filter POP

### ISSUE THREAD

**Issue by elisabethschneider** [sphereio/sphere-sunrise#134]
the customer has a chance to filter the products by select filter by clicking.
you can select as many filter as you wish. 
after each click the page gets automatically refreshed and the new selected page will be shown.
filters can be removed by the clear button

filter types:

        product type
        size
        color
        price
        desingers

**Comment by butenkor** [comment]
Multi select or single select per filter?

**Comment by trangng** [comment]
@butenkor multi select

**Comment by lauraluiz** [comment]
Product type = categories
