### ISSUE TITLE
Create and link screenshot

### ISSUE THREAD

**Issue by schleichardt** [sphereio/sphere-sunrise#14]

**Comment by lauraluiz** [comment]
@schleichardt do you remember what was this about? :)

**Comment by schleichardt** [comment]
I think we should make a screenshot of sunrise and put it into the readme. With link I meant a link to the running demo store.

**Comment by schleichardt** [comment]
I added the label duplicate to make clear that this will be solved in another task.

**Comment by lauraluiz** [comment]
:+1:
