### ISSUE TITLE
add overlay message for selecting facets 

### ISSUE THREAD

**Issue by trangng** [sphereio/sphere-sunrise#178]
after selecting a facet, this message will be shown: 
![20150415_sunrise_02_pop-1_1200_window-please-wait](https://cloud.githubusercontent.com/assets/5373189/10371216/807b3416-6de2-11e5-8f1f-13e8641115c9.png)

@lauraluiz for me the question is what happens, when a customer selects more then one facet at the same time? only the first selection will count?

**Comment by lauraluiz** [comment]
That's what never should happen, and the primary reason of the overlay.
