### ISSUE TITLE
Add product data

### ISSUE THREAD

**Issue by schleichardt** [sphereio/sphere-sunrise#19]
@lauraluiz 
For our new shop, how do we fill the shop with product data? With the client or the CLI? The example product data should be under version control.

**Comment by lauraluiz** [comment]
We already have data, but we still don't have the data in the repo.

**Comment by schleichardt** [comment]
Why don't we have the data in the repo?

**Comment by lauraluiz** [comment]
Data already provided by @CT-Szilvia
