### ISSUE TITLE
Hot reload fails with custom i18n

### ISSUE THREAD

**Issue by lauraluiz** [sphereio/sphere-sunrise#203]

**Comment by schleichardt** [comment]
How to reproduce? What is the error message?

**Comment by lauraluiz** [comment]
I think it happened when the webjars is modified without reloading the project info (so no change of version, just the content changes). Nothing that really affects anybody, but if we can avoid it would be the best.

**Comment by lauraluiz** [comment]
Even though I have been working with i18n a lot and different template versions, I couldn't reproduce it anymore. If it happens again I'll open a new issue.
