### ISSUE TITLE
Change country/language

### ISSUE THREAD

**Issue by lauraluiz** [sphereio/sphere-sunrise#219]
Currently languages and countries are displayed, allow to actually apply the changes.

**Comment by lauraluiz** [comment]
We need to:
- support locales with country of the form `de_AT`
- avoid magic in the code, otherwise it can be unnecessarily hard for developers to change behaviour
- avoid too many mandatory configuration in order to keep Sunrise as a fast deployable project

As we have currently the URL pattern, that leads us to have URLs of the form:
`www.sunrise.com/de_at-AT/...`
Of course that's not very nice, so any other possibility that matches our requirements is welcome @trangng  @mmoelli  @jayS-de @schleichardt

**Comment by mmoelli** [comment]
I guess ```de_at-AT``` is not nice but should fulfil at least for now the requirements w/o waisting too much time.

**Comment by hajoeichler** [comment]
I don't get what this combination means, but if it's country and language, I would do at/de_AT (country/language) or any other better delimiter.

**Comment by lauraluiz** [comment]
@hajoeichler sorry for the lack of explanation. We need to provide a locale (optionally with country variant) for i18n purposes and a country for the cart (taxes, etc). The initial URL pattern was only contemplating a i18n locale without country variant.

**Comment by butenkor** [comment]
at_AT does not exist, right? Why de_AT is not enough? You have language and country in it.

**Comment by lauraluiz** [comment]
The current designed language/country switcher for Sunrise allows you to set any possible combination language-country. It is interesting to have this switcher because it allows a fast visualization of all your project countries/languages when you put your project credentials, without any further configuration.
Therefore you might have a project with:
- languages `de-AT`, `de-DE`, `en`
- countries `DE`, `UK`, `AT`
As the switcher allows you to select any combination, you may pick language `de-AT` with country `UK`, why not. But the question is, how to represent that in the URL?

**Comment by butenkor** [comment]
Most sites force the customer to select country first which is stored as session or cookie or country is preselected by ip locator or defaults to something. Then customer can switch to another language. You need language in URLs for multilingual pages and SEO but i am not sure if you always need it for country too.

**Comment by lauraluiz** [comment]
Yes, that's another option, because I'd say country doesn't affect the SEO ranking. We can keep the country in a cookie. What do others think?

**Comment by schleichardt** [comment]
+1 it was also my suggestion we discussed in person

**Comment by mmoelli** [comment]
I'm fine with that as well.

**Comment by lauraluiz** [comment]
Yes, we discarded it in that moment because we had also the requirement with @jayS-de to be able to change it via the URL as most of us do. But I don't think it's that strong requirement. What's your opinion @jayS-de ?
