### ISSUE TITLE
Gallery check

### ISSUE THREAD

**Issue by lauraluiz** [sphereio/sphere-sunrise#223]
@trangng is there any product with multiple images per variant, so we can check the gallery is properly built?

**Comment by trangng** [comment]
@lauraluiz sorry for my late reply. at the moment we don't have more then one image. have to to add more. I create an issue

**Comment by trangng** [comment]
created one in the porduct import repo https://github.com/sphereio/sphere-product-import/issues/63

**Comment by lauraluiz** [comment]
Thanks!
