### ISSUE TITLE
SEO

### ISSUE THREAD

**Issue by schleichardt** [sphereio/sphere-sunrise#37]
@skedapeda collect the things we need to consider for SEO and make an appointment with @lauraluiz and @schleichardt, please.

**Comment by trangng** [comment]
SEO requirements for SUNRISE are collected here: https://sphere.atlassian.net/wiki/display/SUN/SEO+Requirements

**Comment by butenkor** [comment]
It's an open source project. Having a links to private resources is not very transparent -> outsider will not know what are the requirements we are implementing here

**Comment by schleichardt** [comment]
We will use a per page seo ticket.
