### ISSUE TITLE
Jacoco ignores coverage on Controller actions.

### ISSUE THREAD

**Issue by lauraluiz** [sphereio/sphere-sunrise#61]
```
Result result = callAction(
    controllers.routes.ref.ApplicationController.index(),
    new FakeRequest(GET, "/").withHeader("Accept-Language", lang)
);
```
This is called in `ApplicationControllerTest` but the Jacoco report shows 0% of `index()` method.

**Comment by lauraluiz** [comment]
@schleichardt what's the state of this issue? Was it fixed with the commit?

**Comment by schleichardt** [comment]
No, I need to check Jacoco with the current Play and SBT version.

**Comment by lauraluiz** [comment]
I already removed Jacoco, if there is ever a better alternative we can implement it, but for now it's not necessary.
