### ISSUE TITLE
evaluate play-bootstrap3

### ISSUE THREAD

**Issue by schleichardt** [sphereio/sphere-sunrise#67]
@lauraluiz What do you think of https://github.com/adrianhurt/play-bootstrap3 to use it in a template?

**Comment by lauraluiz** [comment]
I would wait to see the template. As we are probably not going to implement it ourselves, we will have to depend on the template's requirements. If it doesn't use it, then there is no reason for us to use it, as the style would come from the template.

**Comment by lauraluiz** [comment]
I will close this issue unless @JulianSamarjiev tells me we are going to have Bootstrap in the frontend.
