### ISSUE TITLE
Use sphere-sunrise as template module / dependency

### ISSUE THREAD

**Issue by butenkor** [sphereio/sphere-sunrise#69]
It would be great if one could use sunrise as play dependency/module so that most of functionality (routes, controllers, models, views, even some javascript/coffee implementation) would come out from sunrise. New project would then overwrite extend required views/controllers for custom solutions.

**Comment by lauraluiz** [comment]
This is the framework idea, currently not planned for the short-term, since we need to focus first on the demo aspect. But definitely the next step for Sunrise.
