### ISSUE TITLE
Migrate to Play 2.4, SBT 0.13.8 and JVM SDK v1.0.0-M13

### ISSUE THREAD

**Issue by schleichardt** [sphereio/sphere-sunrise#77]
We should move to Play 2.4 since it provides a cool dependency injection mechanism: 

https://www.playframework.com/documentation/2.4.0-M3/JavaDependencyInjection

Since Play 2.4 uses a new Ning version which is backwart incompatible to the current Sphere Play integration classes (M12) I need to release a new SDK version.

**Comment by schleichardt** [comment]
@lgiavedoni @lauraluiz 

I would like to make one pull request to move Sunrise to Play 2.4, please checkin your code on monday.

**Comment by lgiavedoni** [comment]
Hi @schleichardt , 
There is nothing important to commit from my side. Please go ahead with the changes, and I will keep working on the rearchitecture based on those changes, but for now there is nothing that worth committing.
