### ISSUE TITLE
Assertion library for tests

### ISSUE THREAD

**Issue by schleichardt** [sphereio/sphere-sunrise#78]
In Play 2.x except Play 2.4 fest assertions has been used à la `assertThat(list).containsExactly(elem1, elem2)`, In Play 2.4 there is not even a library dependency to fest, what do we gonna use?

* fest
* hamcrest
* JUnit
* other
* self-written?

**Comment by lauraluiz** [comment]
Did they mention the reason why they do not use fest anymore?

**Comment by schleichardt** [comment]
Yes, it is not maintained anymore and the team does not use it for new stuff: 

https://groups.google.com/forum/#!searchin/play-framework-dev/fest/play-framework-dev/C_7KhF7TEzs/ndCqwQ_lT3sJ

**Comment by schleichardt** [comment]
I found a cool one which provides stuff for Java 8. Especially the tester for Exceptions is like I wish it:

http://joel-costigliola.github.io/assertj/assertj-core-features-highlight.html

It could also be interesting to use it for the SDK.
The migration can be easy, since for some things just need imports to be fixed.

**Comment by lauraluiz** [comment]
It looks really good! I'll try to integrate it this week.

**Comment by schleichardt** [comment]
Can I also try it in the SDK?

**Comment by schleichardt** [comment]
Or should I wait?

**Comment by lauraluiz** [comment]
As you wish. If you want to play a bit with it, you can always start with Sunrise that is smaller. Whatever you prefer, really :)

**Comment by lauraluiz** [comment]
Tests are using assertJ and looks nice :+1:
