### ISSUE TITLE
Dependencies in modules

### ISSUE THREAD

**Issue by lgiavedoni** [sphereio/sphere-sunrise#82]
Hi @lauraluiz , @schleichardt ,

Today I was able to make some progress with the new implementations but now I am facing a issue related with the dependencies between modules that I am unable to sort out. 

I need to indicate that our new ProductController extends SunriseController but this is not compiling.

I also tried different alternatives such as adding a dependence on that model to the root: 
lazy val `product-catalog` = project.enablePlugins(PlayJava).dependsOn(`root`)

Any idea on how to get this solved? Thanks

**Comment by schleichardt** [comment]
Oh, we are missing a module for common stuff, products should not depend on root or wepapp.

**Comment by lauraluiz** [comment]
Solved it already.
