### ISSUE TITLE
Testing issue for product-catalog

### ISSUE THREAD

**Issue by lgiavedoni** [sphereio/sphere-sunrise#83]
Hi,

I am trying to add few more tests to our suite for the module product-catalog but I am facing the following issue: seems like the routes are not getting loaded.

So each time that I try to execute any request I am getting: expected:<[200]> but was:<[404]>
If I print out the result I get the following: 

<h2> These routes have been tried, in this order: </h2>
    <div> </div>

The div is empty. But if I do the same with a test defined in the root module then I get the fill list of the routes.

Any idea?

**Comment by lauraluiz** [comment]
Can I try the code myself with your latest commit in the branch `further-structure-template`? Tell me the particular test, so I can reproduce it locally.

**Comment by lgiavedoni** [comment]
Yes, and the test to execute is: sbt test-only controllers.ProductControllerTest
