### ISSUE TITLE
Implementation PDP 

### ISSUE THREAD

**Issue by trangng** [sphereio/sphere-sunrise#87]
Implement PDP based on https://github.com/sphereio/sphere-sunrise-design/issues/2

**Comment by lauraluiz** [comment]
@trangng can you please list what are the MVP for this page?
For example, do we have to implement wishlist, reviews, etc.?

**Comment by lauraluiz** [comment]
And how is the algorithm for the "You may also like" section?

**Comment by lauraluiz** [comment]
And when is a product available? When `stock units > 0`?

**Comment by schleichardt** [comment]
What means "Sunrise #SUN123456" in http://sphereio.github.io/sphere-sunrise-design/pdp.html# ? The second one is probably the SKU but what is the first one?

**Comment by schleichardt** [comment]
What should happen if I click "VIEW DETAILS" in http://sphereio.github.io/sphere-sunrise-design/pdp.html# ?

**Comment by schleichardt** [comment]
Idea: It scrolls to "PRODUCT DETAILS" and opens the accordion?

**Comment by peter-gerhard** [comment]
https://github.com/sphereio/sphere-sunrise-design/blob/master/input/templates/pdp.json#L965

what is the exact meaning of priceOld?

**Comment by hajoeichler** [comment]
If you have a product discount. You want to get the attention of the customer by showing 99.99 strikethrough and 79.99 as new price next to it.

**Comment by schleichardt** [comment]
still internal doc: https://sphere.atlassian.net/wiki/pages/viewpage.action?pageId=19333572

**Comment by trangng** [comment]
@lauraluiz @peter-gerhard MVP for PDP is everything except:
- wishlist
- review

**Comment by schleichardt** [comment]
@trangng What is with inventory?

**Comment by schleichardt** [comment]
I think it would be better to have a whitelist what in this development step needs to be done.

**Comment by trangng** [comment]
algorithm for the "You may also like" section?:
4 products should be shown from
- same gender
- different categories

**Comment by trangng** [comment]
And when is a product available? Yes, when stock units > 0

**Comment by trangng** [comment]
What means "Sunrise #SUN123456" in http://sphereio.github.io/sphere-sunrise-design/pdp.html# ? 
This is the article number. So right text would be e.g.: "Article number CYBORG Z01"

**Comment by trangng** [comment]
What should happen if I click "VIEW DETAILS" in http://sphereio.github.io/sphere-sunrise-design/pdp.html# ? 
If customer clicks on "VIEW DETAILS" the full product description will be shown. Other wise only the first 2 lines.

**Comment by trangng** [comment]
Idea: It scrolls to "PRODUCT DETAILS" and opens the accordion? 

No, under "PRODUCT DETAILS" we show the product attributes e.g.:
Material: 60% viscose, 35% polyamide, 5% elastane
One button on front
Two patch pockets on front
Front longer than back
The model wears a size 38: Dry clean only

**Comment by trangng** [comment]
@schleichardt what do you exactly mean by inventory? the inventory import?

**Comment by schleichardt** [comment]
No, there is a green check mark and right next to it "Available", can we just hardcode it to always be on stock for now?
Adding stock to logic makes not much more to see for demos right now but would kill much time.

**Comment by schleichardt** [comment]
There is no UI element for "VIEW DETAILS" to display further information.

**Comment by JulianSamarjiev** [comment]
@schleichardt I will add that, I wasn't sure myself what is the purpose of having so much text space and 2 accordions for displaying one product's information...

**Comment by trangng** [comment]
No, there is a green check mark and right next to it "Available", can we just hardcode it to always be on stock for now?

@schleichardt ok you can hardcode it for now

**Comment by peter-gerhard** [comment]
is there a specification of how the prices should be formatted?

**Comment by peter-gerhard** [comment]
@trangng can you provide a product with multiple variants that differ in size and color, please?

currently there are a lot of products where the color is not represented in variants but in the product title,
like <actual title> <color> 
see: https://admin.sphere.io/sunrise-staging/products/cfedbda7-55cf-4c1e-9e35-1378a0418c64

for the color and size chooser i need the products to use the model like intended.

**Comment by peter-gerhard** [comment]
"Quantity: you can insert a quantity up to 100 pieces. If there is an insufficient stock, you will get an error message" from https://sphere.atlassian.net/wiki/pages/viewpage.action?pageId=19333572

if its possible to select up to 100 pieces the selection box gets  quite huge, because it tries fit as much choices on the screen as possible, just a minor design issue. for now i will limit the number to 10.

**Comment by butenkor** [comment]
@schleichardt Why adding stock logic to PDP would kill much time? Isn't just fetching inventories for given sku?

**Comment by schleichardt** [comment]
Sunrise is a demo shop, it is not visible by the outside world how much is in the imaginary stock.

**Comment by butenkor** [comment]
Your last statement sounds like a cryptic oracle forecast :) Could you elaborate why demo shop should not show availability infos and it would kill much time?

**Comment by schleichardt** [comment]
It is a demo shop, there is no real stock.

**Comment by butenkor** [comment]
How are you going to show PDP if you have no real product and no real stock?

**Comment by schleichardt** [comment]
Just show the product data and hardcode that is available.

**Comment by butenkor** [comment]
How are you going to add to cart if its not on stock?

**Comment by schleichardt** [comment]
The default cart does not check inventory: 
* http://dev.sphere.io/http-api-projects-carts.html#inventory-mode
* http://dev.sphere.io/http-api-projects-carts.html#inventory-mode

**Comment by butenkor** [comment]
I think its wrong as we should use ```ReserveOnOrder``` by default and should always check if item is on stock before we allow the customer to add to it to a cart. As customer you do not want to make whole checkout process and pay for something which is not stock or even not available anymore. @trangng please check that and specify how we should proceed here.

**Comment by peter-gerhard** [comment]
"Size guide: if you click on the sizeguide a overlay with the measurements will be shown"
@trangng  how is this provided?

**Comment by peter-gerhard** [comment]
@trangng "Product Details" and "Delivery and Returns" are currently simple String types in pdp.json
it would be nicer to show details and shipping methods as lists.

**Comment by trangng** [comment]
@peter-gerhard size guide was done by @JulianSamarjiev I'm not sure if he only have it local or it's not done yet. I'll ask him as soon as he's back from holiday

**Comment by trangng** [comment]
@peter-gerhard I'll talk to @JulianSamarjiev about the tabs "Product Details" and "Delivery and Returns"

**Comment by schleichardt** [comment]
@peter-gerhard In The future, can you include the issue number in the commit message, please?
This way they will be shown here.

Example:
Use `Add sku prefix to ProductData. #87` 
instead of `Add sku prefix`.

**Comment by schleichardt** [comment]
@trangng @peter-gerhard When you want to quote something, then prefix it with `> ` so it is easier to understand:

code: 

```
> Idea: It scrolls to "PRODUCT DETAILS" and opens the accordion?

No, under "PRODUCT DETAILS" we show the product attributes e.g.:
Material: 60% viscose, 35% polyamide, 5% elastane
```

result: 

> Idea: It scrolls to "PRODUCT DETAILS" and opens the accordion?

No, under "PRODUCT DETAILS" we show the product attributes e.g.:
Material: 60% viscose, 35% polyamide, 5% elastane

**Comment by schleichardt** [comment]
Create a new ticket for new questions with the pdp label, please.
