### ISSUE TITLE
choose a template engine

### ISSUE THREAD

**Issue by schleichardt** [sphereio/sphere-sunrise#90]

**Comment by schleichardt** [comment]
TODO: copy wiki page here, contact professional services team

**Comment by butenkor** [comment]
Not sure if understand what you mean here. I thought there is only 1 engine called scala templates, right?

**Comment by schleichardt** [comment]
It is the default template engine, but you can use others, too.

**Comment by butenkor** [comment]
Maybe you can list examples and what would be a benefit of using them?

**Comment by schleichardt** [comment]
:) We have a meeting scheduled for this today.

**Comment by butenkor** [comment]
Still would be great to know in advance what technologies do we consider here.

**Comment by lauraluiz** [comment]
Flexible template engine used, by default Sunrise will use Handlebars.
