### ISSUE TITLE
Update to Play 2.4.0-RC2

### ISSUE THREAD

**Issue by lauraluiz** [sphereio/sphere-sunrise#93]
https://github.com/playframework/playframework/releases/tag/2.4.0-RC2

**Comment by butenkor** [comment]
@lauraluiz Are there any release notes (beside commits) for this version? Do you know when there gonna be stable release of 2.4?

**Comment by schleichardt** [comment]
@butenkor You could search in the mailing list of Play. https://groups.google.com/forum/#!forum/play-framework

I guess 2.4.0 will be out in the beginning of June 2015.

**Comment by butenkor** [comment]
@lauraluiz @schleichardt is there anything you miss in 2.4 compared to 2.3 version?

**Comment by schleichardt** [comment]
Yes, super support of dependency injection. It is more cleaner to create plugins. But it is okay to start with 2.3 and then migrate to 2.4.

**Comment by butenkor** [comment]
Not sure i got it right. ```Yes``` means DI and plugins creation was better in 2.3?

**Comment by schleichardt** [comment]
2.4 has much better DI support.

**Comment by butenkor** [comment]
Thanks. It seem to makes sense to start with 2.4 for new projects considering that we have a nice setup with sunrise already :)

**Comment by schleichardt** [comment]
RC3 is out

**Comment by schleichardt** [comment]
RC5 is out :)

**Comment by lauraluiz** [comment]
I think I'll just wait a bit ;)

**Comment by lauraluiz** [comment]
Currently it is using 2.4.0
